apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot
  labels:
    type: bot
    app: discord
spec:
  replicas: 1
  selector:
    matchLabels:
      type: bot
      app: discord
  template:
    metadata:
      labels:
        type: bot
        app: discord
    spec:
      containers:
        - name: rustcord
          image: "{{ .Values.images.bot.repository }}:{{ .Values.images.bot.tag }}"
          env:
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: BOT_TOKEN
            - name: APPLICATION_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: APPLICATION_ID
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: POSTGRES_HOST
            - name: POSTGRES_PW
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: POSTGRES_PW
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: POSTGRES_USER
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: POSTGRES_DB
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: REDIS_URL
            - name: IMAGES_DIR
              value: /var/mtg_cards
            - name: DISCORD_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: DISCORD_SERVER_URL
            - name: RUST_LOG
              value: warn,rustcord=info,cards_sdk=info
          volumeMounts:
            - name: images
              mountPath: /var/mtg_cards/
              readOnly: true
          {{- with .Values.discordBot.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: images
          hostPath:
            path: {{ .Values.imagesHostPath }}
