apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: postgres
spec:
  endpointSelector:
    matchLabels:
      service: postgres
  ingress:
    - fromEndpoints:
        - matchLabels:
            type: bot
            app: discord
        - matchLabels:
            type: notifier
            app: discord
        - matchLabels:
            job-name: db-migrate
        - matchLabels:
            sync-type: bulk
        - matchLabels:
            sync-type: spoiler
      toPorts:
        - ports:
            - port: "5432"
              protocol: TCP
  egress:
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: redis
spec:
  endpointSelector:
    matchLabels:
      service: redis
  ingress:
    - fromEndpoints:
        - matchLabels:
            type: bot
            app: discord
      toPorts:
        - ports:
            - port: "6379"
              protocol: TCP
  egress:
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
