apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier
  labels:
    type: notifier
    app: discord
spec:
  replicas: 1
  selector:
    matchLabels:
      type: notifier
      app: discord
  template:
    metadata:
      labels:
        type: notifier
        app: discord
    spec:
      containers:
        - name: notifier
          image: "{{ .Values.images.notifier.repository }}:{{ .Values.images.notifier.tag }}"
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: POSTGRES_USER
            - name: POSTGRES_PW
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: POSTGRES_PW
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: POSTGRES_HOST
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: BOT_TOKEN
            - name: IMAGES_DIR
              value: /var/mtg_cards
            - name: RUST_LOG
              value: warn,notifier=info,cards_sdk=info
          volumeMounts:
            - name: images
              mountPath: /var/mtg_cards/
              readOnly: true
          {{- with .Values.notifier.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: images
          hostPath:
            path: {{ .Values.imagesHostPath }}
