secretName: app-secrets

imagesHostPath: /var/mtg_cards/

images:
  postgres:
    repository: postgres
    tag: "18"
  redis:
    repository: redis
    tag: 8-alpine
  bot:
    repository: gitfrog/rustcord
    tag: latest
  notifier:
    repository: gitfrog/rustcord-notifier
    tag: latest

postgres:
  storage: 512Mi
  resources: {}

redis:
  resources: {}

discordBot:
  resources: {}

notifier:
  resources: {}
