name: Deploy The Bot
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Image
        run: docker build -f packages/sync/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/rustcord-sync .

      - name: Push Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/rustcord-sync:latest

  build-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Image
        run: docker build -f packages/bot/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/rustcord .

      - name: Push Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/rustcord:latest

  build-notifier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Image
        run: docker build -f packages/notifier/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/rustcord-notifier .

      - name: Push Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/rustcord-notifier:latest

  deploy:
    needs:
      - build-bot
      - build-sync
      - build-notifier
    if: always() && needs.build-bot.result == 'success' && (needs.build-sync.result == 'success' || needs.build-sync.result == 'skipped') && (needs.build-notifier.result == 'success' || needs.build-notifier.result == 'skipped')
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Apply Secrets
        run: |
          kubectl create secret generic app-secrets \
            --from-literal=BOT_TOKEN=${{ secrets.BOT_TOKEN }} \
            --from-literal=APPLICATION_ID=${{ secrets.APPLICATION_ID }} \
            --from-literal=POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
            --from-literal=POSTGRES_PW=${{ secrets.POSTGRES_PW }} \
            --from-literal=POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
            --from-literal=POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} \
            --from-literal=IMAGES_DIR=${{ secrets.IMAGES_DIR }} \
            --from-literal=REDIS_URL=${{ secrets.REDIS_URL }} \
            --from-literal=USER_AGENT=${{ secrets.USER_AGENT }} \
            --from-literal=DISCORD_SERVER_URL=${{ secrets.DISCORD_SERVER_URL }} \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy via Helm
        run: helm upgrade --install rustcord charts/rustcord

      - name: Restart Bot Deployment
        run: kubectl rollout restart deployment/discord-bot

      - name: Restart Notifier Deployment
        run: kubectl rollout restart deployment/notifier